function [H, forklaringsOutput] = foldningssaetning_med_forklaring(F, G, s, t)
    % FOLDNINGSSAETNING_MED_FORKLARING Demonstrerer foldningssætningen med trinvis forklaring
    %
    % Syntax:
    %   [H, forklaringsOutput] = ElektroMatBibTrinvis.foldningssaetning_med_forklaring(F, G, s, t)
    %
    % Input:
    %   F - første Laplacetransformation som symbolsk udtryk
    %   G - anden Laplacetransformation som symbolsk udtryk
    %   s - Laplace-variabel (symbolsk)
    %   t - tidsvariabel (symbolsk)
    % 
    % Output:
    %   H - produktet F(s)·G(s)
    %   forklaringsOutput - Struktur med forklaringstrin
    
    % Starter forklaring
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.startForklaring('Foldningssætningen for Laplacetransformation');
    
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 1, ...
        'Identificer Laplacetransformationerne', ...
        'Vi starter med de to Laplace-transformerede funktioner.', ...
        ['F(s) = ' char(F) '\nG(s) = ' char(G)]);
    
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 2, ...
        'Forklar foldningssætningen', ...
        'Foldningssætningen siger, at produktet af to Laplacetransformationer svarer til Laplacetransformationen af foldningen af de oprindelige funktioner.', ...
        'L{(f * g)(t)} = F(s) · G(s)');
    
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 3, ...
        'Beregn produktet af Laplacetransformationerne', ...
        'Vi beregner produktet F(s) · G(s).', ...
        ['H(s) = F(s) · G(s) = ' char(F) ' · ' char(G)]);
    
    % Beregn produktet
    H = F * G;
    H_simplified = simplify(H);
    
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 4, ...
        'Simplifiser resultatet', ...
        'Vi forenkler udtrykket om muligt.', ...
        ['H(s) = ' char(H_simplified)]);
    
    % Find den inverse Laplacetransformation
    try
        h = ElektroMatBib.inversLaplace(H_simplified, s, t);
        h_str = char(h);
        
        forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 5, ...
            'Find den tilsvarende foldning i tidsdomænet', ...
            'Ved at anvende invers Laplacetransformation på H(s) finder vi den tilsvarende foldning i tidsdomænet.', ...
            ['h(t) = L^(-1){H(s)} = (f * g)(t) = ' h_str]);
    catch
        forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 5, ...
            'Find den tilsvarende foldning i tidsdomænet', ...
            'Den inverse Laplacetransformation kan være kompleks og kræve yderligere algebraiske manipulationer.', ...
            'h(t) = L^(-1){H(s)} = (f * g)(t)');
    end
    
    % Afslut
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.afslutForklaring(forklaringsOutput, ...
        ['H(s) = ' char(H_simplified)]);
end