
        
        function forklaringsOutput = forklarGenerel(f, t, s, forklaringsOutput)
            % Generel forklaring for andre funktionstyper
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionen som en generel funktion', ...
                'Funktionen passer ikke ind i nogen standardkategori og kræver generel tilgang.', ...
                ['f(t) = ' char(f)]);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Anvend