
        
        function [F, forklaringsOutput] = forklarExpSin(f, t, s, params, forklaringsOutput)
            % Forklaring for dæmpet sinusfunktion
            a = params.a;
            b = params.b;
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionstypen som en dæmpet sinusfunktion', ...
                'Funktionen er på formen e^(at)·sin(bt) for konstanter a og b.', ...
                ['f(t) = e^(' char(a) 't) · sin(' char(b) 't)']);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Brug skiftesætningen (e-reglen)', ...
                ['Hvis vi kend