
        
        function [F, forklaringsOutput] = forklarKonstant(f, t, s, params, forklaringsOutput)
            % Forklaring for konstant funktion
            const_val = params.value;
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionstypen som konstant', ...
                'Da funktionen ikke afhænger af t, er den en konstant funktion.', ...
                ['f(t) = ' char(const_val)]);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Anvend