
        
        function [F, forklaringsOutput] = forklarCos(f, t, s, params, forklaringsOutput)
            % Forklaring for cosinusfunktion
            a = params.a;
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionstypen som en cosinusfunktion', ...
                'Funktionen er på formen cos(at) for en konstant a.', ...
                ['f(t) = cos(' char(a) 't)']);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Brug Eulers formel for at omskrive cosinus', ...
                'Vi kan udtrykke cosinus ved hjælp af komplekse eksponentialfunktioner.', ...
                ['cos(' char(a) 't) = (e^(i·' char(a) 't) + e^(-i·' char(a) 't))/2']);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
                'Anvend