
        
        function [F, forklaringsOutput] = forklarPolynom(f, t, s, params, forklaringsOutput)
            % Forklaring for polynomium
            grad = params.grad;
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionstypen som et polynomium', ...
                ['Funktionen er et polynomium af grad ' num2str(grad) ' i variablen t.'], ...
                ['f(t) = ' char(f)]);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Anvend