
        
        function forklaringsOutput = forklarInversGenerel(F, s, t, forklaringsOutput)
            % Generel forklaring for andre funktionstyper
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionen som en generel Laplacetransformation', ...
                'Funktionen passer ikke ind i nogen standardkategori og kræver generel tilgang.', ...
                ['F(s) = ' char(F)]);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Undersøg mulige manipulationer', ...
                ['Forsøg at manipulere udtrykket algebraisk for at komme til en standardform:\n' ...
                '- Partiel brøkopløsning\n' ...
                '- Komplettere kvadratet i nævneren\n' ...
                '- Anvend