
        
        function [f, forklaringsOutput] = forklarInversDoublePol(F, s, t, params, forklaringsOutput)
            % Forklaring for dobbeltpol
            pol = params.pol;
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionstypen som en brøk med en dobbeltpol', ...
                'Funktionen har en dobbeltpol (pol af orden 2) i s-planen.', ...
                ['F(s) = 1/(s-(' char(pol) '))^2']);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Brug standardformlen for dobbeltpoler', ...
                'Vi kan anvend