
        
        function [f, forklaringsOutput] = forklarInversPartielBrok(F, s, t, params, forklaringsOutput)
            % Forklaring for partiel brøkopløsning
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
                'Identificer funktionstypen som en rationel funktion', ...
                'Funktionen er en rationel funktion, der kan opløses i partialbrøker.', ...
                ['F(s) er en rationel funktion af s']);
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
                'Brug partiel brøkopløsning', ...
                'Vi opløser den rationelle funktion i en sum af simplere brøker.', ...
                'F(s) = A₁/(s-p₁) + A₂/(s-p₂) + ... + B₁/((s-q₁)²+r₁²) + ...');
            
            forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
                'Anvend