% +ElektroMat/+Laplace/forklarSin.m
function [F, forklaringsOutput] = forklarSin(f, t, s, params, forklaringsOutput)
    % Import forklaringssystem functions
    import ElektroMat.Forklaringssystem.*

    % Forklaring for sinusfunktion
    a = params.a;
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en sinusfunktion', ...
        'Funktionen er på formen sin(at) for en konstant a.', ...
        ['f(t) = sin(' char(a) 't)']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 3, ...
        'Brug Eulers formel for at omskrive sinus', ...
        'Vi kan udtrykke sinus ved hjælp af komplekse eksponentialfunktioner.', ...
        ['sin(' char(a) 't) = (e^(i·' char(a) 't) - e^(-i·' char(a) 't))/(2i)']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 4, ...
        'Anvend linearitet af Laplacetransformationen', ...
        'Vi opdeler udtrykket og transformerer de to led separat.', ...
        ['L{sin(' char(a) 't)} = (L{e^(i·' char(a) 't)} - L{e^(-i·' char(a) 't)})/(2i)']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 5, ...
        'Brug standardformlen for eksponentialfunktioner', ...
        'Vi har tidligere udledt at L{e^(kt)} = 1/(s-k).', ...
        ['L{e^(i·' char(a) 't)} = 1/(s-i·' char(a) ')']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 6, ...
        'Indsæt begge transformationer', ...
        'Vi indsætter transformationerne for både e^(i·at) og e^(-i·at).', ...
        ['L{sin(' char(a) 't)} = (1/(s-i·' char(a) ') - 1/(s+i·' char(a) '))/(2i)']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 7, ...
        'Find fællesnævner og omskriv tælleren', ...
        'Vi samler brøkerne under en fælles nævner og finder en simplere form.', ...
        ['L{sin(' char(a) 't)} = ((s+i·' char(a) ') - (s-i·' char(a) '))/(2i·(s-i·' char(a) ')·(s+i·' char(a) '))']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 8, ...
        'Simplificer tælleren og nævneren', ...
        'Vi simplificerer udtrykket for at få det endelige resultat.', ...
        ['L{sin(' char(a) 't)} = (2i·' char(a) ')/(2i·(s^2+' char(a) '^2)) = ' char(a) '/(s^2+' char(a) '^2)']);
    
    % Resultat
    F = a/(s^2 + a^2);
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 9, ...
        'Endelige resultat', ...
        'Laplacetransformationen af sin(at) er:',  ...
        ['L{sin(' char(a) 't)} = ' char(a) '/(s^2+' char(a) '^2) = ' char(F)]);
    
    return;
end