function forklaringsOutput = forklarGenerel(f, t, s, forklaringsOutput)
    % Import forklaringssystem functions
    import ElektroMat.Forklaringssystem.*

    % Generel forklaring for andre funktionstyper
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionen som en generel funktion', ...
        'Funktionen passer ikke ind i nogen standardkategori og kræver generel tilgang.', ...
        ['f(t) = ' char(f)]);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Anvend definitionen af Laplacetransformationen', ...
        'Vi starter med den grundlæggende definition.', ...
        ['L{f(t)} = ∫ f(t) · e^(-st) dt fra 0 til ∞']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Indsæt funktionen i integralet', ...
        'Vi indsætter den konkrete funktion i integralet.', ...
        ['L{' char(f) '} = ∫ ' char(f) ' · e^(-st) dt fra 0 til ∞']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Brug passende integrationsteknikker', ...
        ['For at løse dette integral kan vi bruge teknikker som:\n' ...
        '- Variabelsubstitution\n' ...
        '- Integration ved dele\n' ...
        '- Partiel brøkopløsning\n' ...
        '- Tabelleret integrationstabel'], ...
        '');
    
    return;
end