function [F, forklaringsOutput] = forklarTGangeExp(f, t, s, params, forklaringsOutput)
    % Import forklaringssystem functions
    import ElektroMat.Forklaringssystem.*

    % Forklaring for t ganget med eksponentialfunktion
    a = params.a;
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som t·e^(at)', ...
        'Funktionen er på formen t·e^(at) for en konstant a.', ...
        ['f(t) = t · e^(' char(a) 't)']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 3, ...
        'Anvend differentiationsreglen for Laplacetransformation', ...
        'For L{t·f(t)} bruger vi reglen: L{t·f(t)} = -d/ds[L{f(t)}]', ...
        ['Først finder vi L{e^(' char(a) 't)} = 1/(s-(' char(a) '))']);
    
    % Beregn først L{e^(at)}
    F_exp = 1/(s - a);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 4, ...
        'Beregn Laplacetransformationen af e^(at)', ...
        'Vi har fra tidligere at L{e^(at)} = 1/(s-a) for Re{s} > Re{a}:', ...
        ['L{e^(' char(a) 't)} = ' char(F_exp)]);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 5, ...
        'Anvend t-multiplikationsreglen', ...
        'Nu anvender vi reglen L{t·f(t)} = -d/ds[F(s)]:', ...
        ['L{t·e^(' char(a) 't)} = -d/ds[1/(s-(' char(a) '))]']);
    
    % Beregn den afledte
    F_afledt = diff(F_exp, s);
    F = -F_afledt;
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 6, ...
        'Beregn den afledte', ...
        'Vi differentierer 1/(s-a) med hensyn til s:', ...
        ['d/ds[1/(s-(' char(a) '))] = d/ds[(s-(' char(a) '))^(-1)] = -1·(s-(' char(a) '))^(-2) = -1/(s-(' char(a) '))^2']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 7, ...
        'Anvend fortegnskiftet fra t-multiplikationsreglen', ...
        'Med minus-tegnet fra reglen får vi:', ...
        ['L{t·e^(' char(a) 't)} = -(-1/(s-(' char(a) '))^2) = 1/(s-(' char(a) '))^2']);
    
    % Resultat
    F = 1/(s - a)^2;
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 8, ...
        'Verificer resultatet', ...
        'Vi kan verificere ved at differentiere den inverse transformation:', ...
        ['L^(-1){1/(s-a)^2} = t·e^(at)·u(t) ✓']);
    
    forklaringsOutput = tilfoejTrin(forklaringsOutput, 9, ...
        'Endelige resultat', ...
        'Laplacetransformationen af t·e^(at) er:', ...
        ['L{t·e^(' char(a) 't)} = 1/(s-(' char(a) '))^2 = ' char(F) ' for Re{s} > Re{' char(a) '}']);
    
    return;
end