function [F, forklaringsOutput] = forklarExp(f, t, s, params, forklaringsOutput)
    % Forklaring for eksponentialfunktion
    a = params.a;
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en eksponentialfunktion', ...
        'Funktionen er på formen e^(at) for en konstant a.', ...
        ['f(t) = e^(' char(a) 't)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Anvend definitionen af Laplacetransformationen', ...
        'Vi indsætter funktionen i integralformlen for Laplacetransformationen.', ...
        ['L{f(t)} = ∫ e^(' char(a) 't) · e^(-st) dt fra 0 til ∞']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Kombinér eksponentialerne', ...
        'Vi kan kombinere eksponenterne ved at bruge regnereglerne for eksponentialfunktioner.', ...
        ['L{f(t)} = ∫ e^((' char(a) '-s)t) dt fra 0 til ∞']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Integrér udtrykket', ...
        'Integralet af e^(kt) med hensyn til t er e^(kt)/k, for en konstant k.', ...
        ['L{f(t)} = [e^((' char(a) '-s)t)/(' char(a) '-s)]_0^∞']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 6, ...
        'Indsæt integrationsgrænser og undersøg konvergens', ...
        ['For at integralet skal konvergere, kræves det at Re(s) > Re(' char(a) ').'], ...
        ['Under denne betingelse går e^((' char(a) '-s)t) mod 0 når t går mod uendelig.']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 7, ...
        'Udregn det endelige resultat', ...
        'Ved at indsætte grænserne får vi:',  ...
        ['L{f(t)} = 0 - (1/(' char(a) '-s)) = 1/(s-' char(a) ')']);
    
    % Resultat
    F = 1/(s - a);
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 8, ...
        'Simplifiser resultatet', ...
        'Det endelige resultat kan evt. omskrives til standardform.', ...
        ['L{f(t)} = 1/(s-(' char(a) ')) = ' char(F)]);
    
    return;
end