function [F, forklaringsOutput] = forklarExpSin(f, t, s, params, forklaringsOutput)
    % Import forklaringssystem functions
    import ElektroMat.Forklaringssystem.*

    % Forklaring for dæmpet sinusfunktion
    a = params.a;
    b = params.b;
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en dæmpet sinusfunktion', ...
        'Funktionen er på formen e^(at)·sin(bt) for konstanter a og b.', ...
        ['f(t) = e^(' char(a) 't) · sin(' char(b) 't)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Brug skiftesætningen (e-reglen)', ...
        ['Hvis vi kender L{g(t)} = G(s), så gælder: L{e^(at)·g(t)} = G(s-a).'], ...
        ['Vi ved at L{sin(' char(b) 't)} = ' char(b) '/(s^2+' char(b) '^2)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Anvend skiftesætningen', ...
        ['Vi erstatter s med (s-' char(a) ') i transformationen af sin(' char(b) 't).'], ...
        ['L{e^(' char(a) 't)·sin(' char(b) 't)} = ' char(b) '/((s-' char(a) ')^2+' char(b) '^2)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Ekspandér nævneren', ...
        'Vi kan ekspandere udtrykket i nævneren for at få standardformen.', ...
        ['(s-' char(a) ')^2+' char(b) '^2 = s^2-2' char(a) 's+' char(a) '^2+' char(b) '^2']);
    
    % Resultat
    F = b/((s-a)^2 + b^2);
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 6, ...
        'Endelige resultat', ...
        'Laplacetransformationen af den dæmpede sinusfunktion er:',  ...
        ['L{e^(' char(a) 't)·sin(' char(b) 't)} = ' char(F)]);
    
    return;
end