function [F, forklaringsOutput] = enhedsTrin_med_forklaring(t0, t, s)
    % ENHEDSTRIN_MED_FORKLARING Forklarer enhedstrinfunktionen og dens Laplacetransformation
    %
    % Syntax:
    %   [F, forklaringsOutput] = ElektroMatBibTrinvis.enhedsTrin_med_forklaring(t0, t, s)
    %
    % Input:
    %   t0 - forskydning af enhedstrinfunktionen
    %   t - tidsvariabel (symbolsk)
    %   s - Laplace-variabel (symbolsk)
    % 
    % Output:
    %   F - Laplacetransformationen af u(t-t0)
    %   forklaringsOutput - Struktur med forklaringstrin
    
    % Starter forklaring
    forklaringsOutput = ElektroMatBibTrinvis.startForklaring('Enhedstrinfunktionen');
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 1, ...
        'Definér enhedstrinfunktionen', ...
        'Enhedstrinfunktionen u(t) repræsenterer et spring fra 0 til 1 ved tiden t = 0.', ...
        ['u(t-' char(t0) ') = { 1 for t ≥ ' char(t0) ', 0 for t < ' char(t0) ' }']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Egenskaber for enhedstrinfunktionen', ...
        ['Følgende egenskaber gælder for enhedstrinfunktionen:\n' ...
        '1. u(t) er diskontinuert ved t = 0\n' ...
        '2. d/dt[u(t)] = δ(t) (enhedstrinfunktionen er integralet af delta-funktionen)\n' ...
        '3. f(t)·u(t-t0) "tænder" for f(t) ved tiden t = t0'], ...
        '');
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Anvend definitionen for Laplacetransformationen', ...
        'Vi anvender definitionen af Laplacetransformationen på enhedstrinfunktionen.', ...
        ['L{u(t-' char(t0) ')} = ∫ u(t-' char(t0) ')·e^(-st) dt fra 0- til ∞']);
    
    % Resultat afhænger af t0
    if t0 > 0
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
            'Opdel integralet', ...
            ['Da ' char(t0) ' > 0, starter springet efter t = 0:'], ...
            ['∫ u(t-' char(t0) ')·e^(-st) dt = ∫ 0·e^(-st) dt fra 0 til ' char(t0) ' + ∫ 1·e^(-st) dt fra ' char(t0) ' til ∞']);
        
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
            'Beregn integralet', ...
            ['Vi løser integralet:'], ...
            ['∫ e^(-st) dt fra ' char(t0) ' til ∞ = [-e^(-st)/s]_' char(t0) '^∞ = 0 - (-e^(-s·' char(t0) ')/s) = e^(-s·' char(t0) ')/s']);
        
        F = exp(-s*t0)/s;
    elseif t0 == 0
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
            'Simpelt tilfælde for t0 = 0', ...
            'For t0 = 0 har vi den klassiske enhedstrinfunktion u(t).', ...
            ['∫ u(t)·e^(-st) dt = ∫ 1·e^(-st) dt fra 0 til ∞ = [-e^(-st)/s]_0^∞ = 0 - (-1/s) = 1/s']);
        
        F = 1/s;
    else % t0 < 0
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
            'Analysér tilfældet t0 < 0', ...
            ['Da ' char(t0) ' < 0, starter springet før t = 0, så u(t-' char(t0) ') = 1 for hele integrationsområdet [0,∞).'], ...
            ['∫ u(t-' char(t0) ')·e^(-st) dt = ∫ 1·e^(-st) dt fra 0 til ∞ = 1/s']);
        
        F = 1/s;
    end
    
    % Anvend forsinkelsesreglen
    if t0 > 0
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 6, ...
            'Brug forsinkelsesreglen', ...
            ['Vi kan også anvende forsinkelsesreglen direkte:'], ...
            ['L{u(t-' char(t0) ')} = L{u(t)}·e^(-s·' char(t0) ') = (1/s)·e^(-s·' char(t0) ') = e^(-s·' char(t0) ')/s']);
    end
    
    % Afslut
    forklaringsOutput = ElektroMatBibTrinvis.afslutForklaring(forklaringsOutput, ...
        ['L{u(t-' char(t0) ')} = ' char(F)]);
end