function [f, forklaringsOutput] = forklarInversDoublePol(F, s, t, params, forklaringsOutput)
    % Forklaring for dobbeltpol
    pol = params.pol;
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en brøk med en dobbeltpol', ...
        'Funktionen har en dobbeltpol (pol af orden 2) i s-planen.', ...
        ['F(s) = 1/(s-(' char(pol) '))^2']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Brug standardformlen for dobbeltpoler', ...
        'Vi kan anvende en velkendt relation fra tabellen over inverse Laplacetransformationer.', ...
        ['L^(-1){1/(s-a)^2} = t·e^(at)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Indsæt værdien for polen', ...
        ['Vi indsætter a = ' char(pol) ' i standardformlen.'], ...
        ['L^(-1){1/(s-(' char(pol) '))^2} = t·e^(' char(pol) 't)']);
    
    % Resultat
    f = t*exp(pol*t);
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Udtryk det endelige resultat', ...
        'Den inverse Laplacetransformation er produktet af t og en eksponentialfunktion.', ...
        ['f(t) = t·e^(' char(pol) 't) for t ≥ 0']);
    
    return;
end