function [f, forklaringsOutput] = forklarInversKonstant(F, s, t, params, forklaringsOutput)
    % Forklaring for konstant Laplacefunktion
    const_val = params.value;
    
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en konstant', ...
        'Laplacetransformationen er en konstant, uafhængig af s.', ...
        ['F(s) = ' char(const_val)]);
    
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 3, ...
        'Brug egenskaber for invers Laplacetransformation af konstanter', ...
        'For konstanter gælder specielle regler relateret til impulsfunktionen.', ...
        ['L^(-1){k} = k · δ(t), hvor δ(t) er Dirac delta-funktionen']);
    
    % Resultat - formelt set ville dette være dirac delta, men for enkelhedens skyld
    f = const_val * sym('dirac(t)');
    forklaringsOutput = ElektroMatBibTrinvis.ElektroMat.Forklaringssystem.tilfoejTrin(forklaringsOutput, 4, ...
        'Formuler det endelige resultat', ...
        'Den inverse Laplacetransformation er en impulsfunktion.', ...
        ['f(t) = ' char(const_val) ' · δ(t)']);
    
    return;
end