function forklaringsOutput = forklarInversGenerel(F, s, t, forklaringsOutput)
    % Import forklaringssystem functions
    import ElektroMat.Forklaringssystem.*

    % Generel forklaring for andre funktionstyper
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionen som en generel Laplacetransformation', ...
        'Funktionen passer ikke ind i nogen standardkategori og kræver generel tilgang.', ...
        ['F(s) = ' char(F)]);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Undersøg mulige manipulationer', ...
        ['Forsøg at manipulere udtrykket algebraisk for at komme til en standardform:\n' ...
        '- Partiel brøkopløsning\n' ...
        '- Komplettere kvadratet i nævneren\n' ...
        '- Anvende skiftesætninger'], ...
        '');
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Brug opslag i tabel over inverse Laplacetransformationer', ...
        'Konsulter en tabel over kendte par af Laplacetransformationer.', ...
        'Eller anvend definitionsintegralet for invers Laplacetransformation.');
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Anvend linearitet af invers Laplacetransformation', ...
        'Opdel evt. i simplere dele som kan transformeres separat.', ...
        'L^(-1){aF₁(s) + bF₂(s)} = aL^(-1){F₁(s)} + bL^(-1){F₂(s)}');
    
    return;
end