function [F, forklaringsOutput] = deltaFunktionMedForklaring(t0, t, s)
    % Import forklaringssystem functions
    import ElektroMat.Forklaringssystem.*

    % DELTAFUNKTION_MED_FORKLARING Forklarer Dirac's delta-funktion og dens Laplacetransformation
    %
    % Syntax:
    %   [F, forklaringsOutput] = ElektroMatBibTrinvis.deltaFunktionMedForklaring(t0, t, s)
    %
    % Input:
    %   t0 - tidspunkt for impulsen
    %   t - tidsvariabel (symbolsk)
    %   s - Laplace-variabel (symbolsk)
    % 
    % Output:
    %   F - Laplacetransformationen af delta(t-t0)
    %   forklaringsOutput - Struktur med forklaringstrin
    
    % Starter forklaring
    forklaringsOutput = ElektroMatBibTrinvis.startForklaring('Diracs Delta-funktion');
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 1, ...
        'Definér delta-funktionen', ...
        'Diracs delta-funktion er en generaliseret funktion, der repræsenterer en uendelig smal og høj impuls.', ...
        ['δ(t-' char(t0) ') = { ∞ for t = ' char(t0) ', 0 for t ≠ ' char(t0) ' }']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Egenskaber for delta-funktionen', ...
        ['Følgende egenskaber gælder for delta-funktionen:\n' ...
        '1. ∫ δ(t-' char(t0) ') dt = 1 (areal = 1)\n' ...
        '2. ∫ f(t)·δ(t-' char(t0) ') dt = f(' char(t0) ') (sampling-egenskab)\n' ...
        '3. δ(t) = d/dt[u(t)] (differentialet af enhedstrinfunktionen)'], ...
        '');
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Anvend definitionen for Laplacetransformationen', ...
        'Vi anvender definitionen af Laplacetransformationen på delta-funktionen.', ...
        ['L{δ(t-' char(t0) ')} = ∫ δ(t-' char(t0) ')·e^(-st) dt fra 0- til ∞']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Udnyt sampling-egenskaben', ...
        ['Ved at bruge sampling-egenskaben med f(t) = e^(-st), får vi:'], ...
        ['∫ δ(t-' char(t0) ')·e^(-st) dt = e^(-s·' char(t0) ')']);
    
    % Resultat afhænger af t0
    if t0 < 0
        F = 0;
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
            'Vurdér intervallet', ...
            ['Da ' char(t0) ' < 0, ligger delta-impulsen uden for integrationsområdet [0,∞).'], ...
            ['L{δ(t-' char(t0) ')} = 0 for ' char(t0) ' < 0']);
    else
        F = exp(-s*t0);
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
            'Beregn transformationen', ...
            ['Da ' char(t0) ' ≥ 0, har vi:'], ...
            ['L{δ(t-' char(t0) ')} = e^(-s·' char(t0) ')']);
    end
    
    % Specielt tilfælde hvis t0 = 0
    if t0 == 0
        forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 6, ...
            'Specielt tilfælde for t0 = 0', ...
            'For t0 = 0 har vi delta-funktionen centreret i 0.', ...
            'L{δ(t)} = 1');
    end
    
    % Afslut
    forklaringsOutput = ElektroMatBibTrinvis.afslutForklaring(forklaringsOutput, ...
        ['L{δ(t-' char(t0) ')} = ' char(F)]);
end