function [f, forklaringsOutput] = forklarInversSimplePol(F, s, t, params, forklaringsOutput)
    % Forklaring for simpel pol
    pol = params.pol;
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en brøk med en simpel pol', ...
        'Funktionen har en simpel pol i s-planen.', ...
        ['F(s) = 1/(s-(' char(pol) '))']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Brug standardformlen for simple poler', ...
        'Vi kan anvende en velkendt relation fra tabellen over inverse Laplacetransformationer.', ...
        ['L^(-1){1/(s-a)} = e^(at)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Indsæt værdien for polen', ...
        ['Vi indsætter a = ' char(pol) ' i standardformlen.'], ...
        ['L^(-1){1/(s-(' char(pol) '))} = e^(' char(pol) 't)']);
    
    % Resultat
    f = exp(pol*t);
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Udtryk det endelige resultat', ...
        'Den inverse Laplacetransformation er en eksponentialfunktion.', ...
        ['f(t) = e^(' char(pol) 't) for t ≥ 0']);
    
    return;
end