function [F, forklaringsOutput] = forklarCos(f, t, s, params, forklaringsOutput)
    % Forklaring for cosinusfunktion
    a = params.a;
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 2, ...
        'Identificer funktionstypen som en cosinusfunktion', ...
        'Funktionen er på formen cos(at) for en konstant a.', ...
        ['f(t) = cos(' char(a) 't)']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 3, ...
        'Brug Eulers formel for at omskrive cosinus', ...
        'Vi kan udtrykke cosinus ved hjælp af komplekse eksponentialfunktioner.', ...
        ['cos(' char(a) 't) = (e^(i·' char(a) 't) + e^(-i·' char(a) 't))/2']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 4, ...
        'Anvend linearitet af Laplacetransformationen', ...
        'Vi opdeler udtrykket og transformerer de to led separat.', ...
        ['L{cos(' char(a) 't)} = (L{e^(i·' char(a) 't)} + L{e^(-i·' char(a) 't)})/2']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 5, ...
        'Brug standardformlen for eksponentialfunktioner', ...
        'Vi har tidligere udledt at L{e^(kt)} = 1/(s-k).', ...
        ['L{e^(i·' char(a) 't)} = 1/(s-i·' char(a) ')']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 6, ...
        'Indsæt begge transformationer', ...
        'Vi indsætter transformationerne for både e^(i·at) og e^(-i·at).', ...
        ['L{cos(' char(a) 't)} = (1/(s-i·' char(a) ') + 1/(s+i·' char(a) '))/2']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 7, ...
        'Find fællesnævner og omskriv tælleren', ...
        'Vi samler brøkerne under en fælles nævner og finder en simplere form.', ...
        ['L{cos(' char(a) 't)} = ((s+i·' char(a) ') + (s-i·' char(a) '))/(2·(s-i·' char(a) ')·(s+i·' char(a) '))']);
    
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 8, ...
        'Simplificer tælleren og nævneren', ...
        'Vi simplificerer udtrykket for at få det endelige resultat.', ...
        ['L{cos(' char(a) 't)} = (2s)/(2·(s^2+' char(a) '^2)) = s/(s^2+' char(a) '^2)']);
    
    % Resultat
    F = s/(s^2 + a^2);
    forklaringsOutput = ElektroMatBibTrinvis.tilfoejTrin(forklaringsOutput, 9, ...
        'Endelige resultat', ...
        'Laplacetransformationen af cos(at) er:',  ...
        ['L{cos(' char(a) 't)} = s/(s^2+' char(a) '^2) = ' char(F)]);
    
    return;
end